### ISSUE TITLE
multiprocessing.pool.RemoteTraceback: 

### ISSUE THREAD

**Issue by damientully** [khyox/recentrifuge#1]
Hi, 

I am trying to use recentrifuge and I get the following error:
 
`=-= recentrifuge.py =-= v0.18.3 =-= Mar 2018 =-=

Loading NCBI nodes... OK! 
Loading NCBI names... OK! 
Building dict of parent to children taxa... OK! 

Please, wait, processing files in parallel...

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/damientully/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/damientully/Downloads/recentrifuge-master/recentrifuge/centrifuge.py", line 102, in process_report
    tree.prune(mintaxa, None, collapse, debug)
  File "/Users/damientully/Downloads/recentrifuge-master/recentrifuge/trees.py", line 471, in prune
    and self[tid].prune(min_taxa, min_rank, collapse, debug)):
  File "/Users/damientully/Downloads/recentrifuge-master/recentrifuge/trees.py", line 471, in prune
    and self[tid].prune(min_taxa, min_rank, collapse, debug)):
  File "/Users/damientully/Downloads/recentrifuge-master/recentrifuge/trees.py", line 471, in prune
    and self[tid].prune(min_taxa, min_rank, collapse, debug)):
  [Previous line repeated 3 more times]
  File "/Users/damientully/Downloads/recentrifuge-master/recentrifuge/trees.py", line 484, in prune
    self.score = ((self.score * self.counts
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "recentrifuge.py", line 624, in <module>
    main()
  File "recentrifuge.py", line 597, in main
    read_samples()
  File "recentrifuge.py", line 329, in read_samples
    input_files, [r.get() for r in async_results]):
  File "recentrifuge.py", line 329, in <listcomp>
    input_files, [r.get() for r in async_results]):
  File "/Users/damientully/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`

**Comment by khyox** [comment]
Hi. Thanks for reporting an issue. Could you please tell me the complete command line that you are using to launch Recentrifuge?

**Comment by damientully** [comment]
Sure its
` ./recentrifuge.py -r Run58_4_kreport.txt`

**Comment by damientully** [comment]
Ah thanks. No I can use either. Just used the scores file and that worked!

Thanks again!
