### ISSUE TITLE
KeyError: 'STRAIN'

### ISSUE THREAD

**Issue by abomba** [khyox/recentrifuge#23]
Hi, can you help me with this issues?

# Bug report
```
=-= /home/abomba/miniconda3/bin/rcf =-= v1.0.3 - May 2020 =-= by Jose Manuel Martí =-=

Loading NCBI nodes...Traceback (most recent call last):
  File "/home/abomba/miniconda3/lib/python3.6/site-packages/recentrifuge/taxonomy.py", line 79, in read_nodes
    rank = Rank[_rank.upper().replace(" ", "_")]
  File "/home/abomba/miniconda3/lib/python3.6/enum.py", line 329, in __getitem__
    return cls._member_map_[name]
KeyError: 'STRAIN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abomba/miniconda3/bin/rcf", line 813, in <module>
    main()
  File "/home/abomba/miniconda3/bin/rcf", line 737, in main
    collapse, excluding, including, args.debug)
  File "/home/abomba/miniconda3/lib/python3.6/site-packages/recentrifuge/taxonomy.py", line 40, in __init__
    self.read_nodes(nodes_file)
  File "/home/abomba/miniconda3/lib/python3.6/site-packages/recentrifuge/taxonomy.py", line 82, in read_nodes
    f'Unknown tax level {_rank}')
recentrifuge.rank.UnsupportedTaxLevelError: Unknown tax level strain
```

#### Command line

```
> rcf -f s.tsv -n ~/miniconda3/bin/taxdump
```

### Versions 

  * Operating system: Ubuntu 16.04
  * Python version: 3.6
  * Recentrifuge version: rcf version 1.0.3 released in May 2020

**Comment by khyox** [comment]
Hi @abomba and thank you very much for reporting this! It seems that NCBI has introduced an important change in its taxonomy in the last days which breaks Recentrifuge. Let me confirm that and I will come back with a solution. Thanks.

**Comment by gaferguz** [comment]
Hi, i am facing the same issue with recentrifuge, but im not sure if it is a matter of reinstalling or running an specific script on my computer. ¿What should I do?

```
Loading` NCBI nodes...Traceback (most recent call last):
  File "/home/gabriel/.local/lib/python3.7/site-packages/recentrifuge/taxonomy.py", line 79, in read_nodes
    rank = Rank[_rank.upper().replace(" ", "_")]
  File "/home/gabriel/anaconda3/lib/python3.7/enum.py", line 352, in __getitem__
    return cls._member_map_[name]
KeyError: 'STRAIN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriel/.local/bin/rcf", line 813, in <module>
    main()
  File "/home/gabriel/.local/bin/rcf", line 737, in main
    collapse, excluding, including, args.debug)
  File "/home/gabriel/.local/lib/python3.7/site-packages/recentrifuge/taxonomy.py", line 40, in __init__
    self.read_nodes(nodes_file)
  File "/home/gabriel/.local/lib/python3.7/site-packages/recentrifuge/taxonomy.py", line 82, in read_nodes
    f'Unknown tax level {_rank}')
recentrifuge.rank.UnsupportedTaxLevelError: Unknown tax level strain

```

**Comment by khyox** [comment]
Hi @gaferguz, please update Recentrifuge to the latest version and try again. If you still have the issue or you already has the latest version, please open another issue so that you provide all the information I need to try to reproduce and correct it. Thanks!

**Comment by gaferguz** [comment]
Hi @khyox , I have reinstalled the latest version and everything seem to be working fine, thanks for your quick response.

**Comment by khyox** [comment]
Thanks for the feedback. Enjoy!
