### ISSUE TITLE
Bug Report: PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by hansir8** [khyox/recentrifuge#24]
Here is the bug report of recentrifuge.
The error is list below:
-------->
=-= /home/Software/Miniconda3/envs/poliolab-ngs-env/bin/rcf =-= v1.1.0 - Jun 2020 =-= by Jose M
anuel Martí =-=

Loading NCBI nodes... OK! 
Loading NCBI names... OK! 
Building dict of parent to children taxa... OK! 

Please, wait, processing files in parallel...

Traceback (most recent call last):
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/bin/rcf", line 836, in <module>
    main()
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/bin/rcf", line 795, in main
    read_samples()
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/bin/rcf", line 461, in read_samples
    len(input_files))) as pool:
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/lib/python3.6/multiprocessing/pool.py", line 156, in __init__
    self._setup_queues()
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/lib/python3.6/multiprocessing/pool.py", line 249, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/lib/python3.6/multiprocessing/queues.py", line 315, in __init__
    self._rlock = ctx.Lock()
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/home/Software/Miniconda3/envs/poliolab-ngs-env/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied
----------->

The command line is:
-------->
 rcf -n /Database/taxdump/ -k 03.Reads.classify/kraken2_classification_result -e FULL -o 03.Reads.classify/classification.kraken2.html
--------->

I have test the version v1.1.0 and v1.1.1, and all appear this error. Can you provide a solution for this ?

**Comment by khyox** [comment]
The PermissionError exception is quite self-explanatory and it usually is raised in that part of the code if you have not read permissions on the directory or the files you are trying to read. Please check that you have the proper permissions on the  `03.Reads.classify/kraken2_classification_result` directory. To check it, you can issue a `ls -l 03.Reads.classify/kraken2_classification_result` command and check the output.

**Comment by hansir8** [comment]
Thanks for your quick reply!  I have tried this solution using the command line.
------>
chmod -R 755 03.Reads.classify/ 
------->
However, I also meet this problem using the common user. When I used the root user, the problem was solved successfully. I speculated that the conda environment permission could caused this question. Thanks very much for your help again! 

Zhenzhi Han

**Comment by khyox** [comment]
Thanks for the feedback, Zhenzhi! 
I am glad that you could solve that issue. It seems very specific to the bioconda environment.
Enjoy recentrifuge!
